import { ScrollTimelineEntry } from "@/types/scroll";

export const scrollTimeline: ScrollTimelineEntry[] = [
  {
    id: "about",
    label: "About",
    command: "about",
    summary: "Get the quick story and focus areas.",
    content: [
      "I build production-ready AI/ML tooling that bridges rigorous research with practical engineering across security, code intelligence, and automation.",
      "Current work centers on vulnerability-aware copilots, RAG-enhanced workflows, and inference/training pipelines that prioritize reliability and observability.",
      "I hold an Honours BSc in Computer Science (Data Analytics) and stay embedded with applied research partners.",
    ],
  },
  {
    id: "skills",
    label: "Skills",
    command: "skills",
    summary: "See the grouped stack and tooling.",
    iconGroups: [
      {
        title: "Programming Languages",
        items: [
          { label: "Python", badgeSrc: "/badges/python.svg" },
          { label: "JavaScript", badgeSrc: "/badges/javascript.svg" },
          { label: "TypeScript", badgeSrc: "/badges/typescript.svg" },
          { label: "Solidity", badgeSrc: "/badges/solidity.svg" },
          { label: "Rust", badgeSrc: "/badges/rust.svg" },
          { label: "C#", badgeSrc: "/badges/csharp.svg" },
          { label: "R", badgeSrc: "/badges/r.svg" },

        ],
      },
      {
        title: "AI, Data & ML Stack",
        items: [
          { label: "PyTorch", badgeSrc: "/badges/pytorch.svg" },
          { label: "TensorFlow", badgeSrc: "/badges/tensorflow.svg" },
          { label: "Hugging Face", badgeSrc: "/badges/hugging-face.svg" },
          { label: "Transformers", badgeSrc: "/badges/transformers.svg" },
          { label: "Unsloth", badgeSrc: "/badges/unsloth.svg" },
          { label: "vLLM", badgeSrc: "/badges/vllm.svg" },
          { label: "DeepSpeed", badgeSrc: "/badges/deepspeed.svg" },
          { label: "Pandas", badgeSrc: "/badges/pandas.svg" },
          { label: "NumPy", badgeSrc: "/badges/numpy.svg" },
          { label: "Tableau", badgeSrc: "/badges/tableau.svg" },
          { label: "Power BI", badgeSrc: "/badges/power-bi.svg" },
        ],
      },
      {
        title: "Full Stack",
        items: [
          { label: "HTML5", badgeSrc: "/badges/html5.svg" },
          { label: "CSS3", badgeSrc: "/badges/css3.svg" },
          { label: "React", badgeSrc: "/badges/react.svg" },
          { label: "Next.js", badgeSrc: "/badges/next-js.svg" },
          { label: "Node.js", badgeSrc: "/badges/node-js.svg" },
          { label: "Express", badgeSrc: "/badges/express.svg" },
          { label: "FastAPI", badgeSrc: "/badges/fastapi.svg" },
          { label: "Django", badgeSrc: "/badges/django.svg" },
          { label: "Flask", badgeSrc: "/badges/flask.svg" },
          { label: "PostgreSQL", badgeSrc: "/badges/postgresql.svg" },
          { label: "MongoDB", badgeSrc: "/badges/mongodb.svg" },
          { label: "MySQL", badgeSrc: "/badges/mysql.svg" },
          { label: "SQLite", badgeSrc: "/badges/sqlite.svg" },
          { label: "Milvus", badgeSrc: "/badges/milvus.svg" },
          { label: "Flutter", badgeSrc: "/badges/flutter.svg" },
        ],
      },
      {
        title: "Infra, DevOps & Tooling",
        items: [
          { label: "AWS", badgeSrc: "/badges/aws.svg" },
          { label: "Google Cloud", badgeSrc: "/badges/google-cloud.svg" },
          { label: "Azure", badgeSrc: "/badges/azure.svg" },
          { label: "Docker", badgeSrc: "/badges/docker.svg" },
          { label: "Git", badgeSrc: "/badges/git.svg" },
          { label: "Vercel", badgeSrc: "/badges/vercel.svg" },
          { label: "Netlify", badgeSrc: "/badges/netlify.svg" },
          { label: "Heroku", badgeSrc: "/badges/heroku.svg" },
          { label: "Firebase", badgeSrc: "/badges/firebase.svg" },
          { label: "Cloudflare", badgeSrc: "/badges/cloudflare.svg" },
          { label: "Linux", badgeSrc: "/badges/linux.svg" },
          { label: "Nginx", badgeSrc: "/badges/nginx.svg" },
          { label: "Postman", badgeSrc: "/badges/postman.svg" },
        ],
      },
    ],
    content: [],
  },
  {
    id: "experience",
    label: "Experience",
    command: "experience",
    summary: "Chronological roles and highlights.",
    timeline: [
      {
        company: "CredShields",
        companyUrl: "https://credshields.com/",
        role: "AI Engineer & ML Researcher",
        duration: "Apr 2025 – Present",
        location: "Part-time · Remote (Singapore)",
        isCurrent: true,
        details: [
          "Led LLM-assisted pipelines that spot smart contract vulnerabilities.",
          "Built RAG workflows and knowledge bases to make copilots actionable.",
          "Fine-tuned PyTorch/Hugging Face models for few-shot vulnerability questions.",
        ],
      },
      {
        company: "TELUS",
        companyUrl: "https://www.telus.com/en",
        role: "Machine Learning Researcher",
        duration: "Jan 2025 – Apr 2025",
        location: "Part-time · Oakville, Ontario",
        details: [
          "Architected a generative-AI indoor localization system with research partners.",
          "Synthesized RSSI data with VAEs to auto-generate virtual fingerprints.",
          "Validated nearest-neighbor regression on 2D layouts for precise positioning.",
        ],
      },
      {
        company: "McMaster University",
        companyUrl: "https://www.mcmaster.ca/",
        role: "Full Stack Developer",
        duration: "Sep 2024 – Dec 2024",
        location: "Part-time · Oakville, Ontario",
        details: [
          "Ported a web experience into a Flutter-powered iOS/Android build.",
          "Enhanced UX, enforced GDPR/HIPAA compliance, and integrated Strapi + SQL.",
          "Iterated via Figma, REST APIs, and Git-based review cycles.",
        ],
      },
      {
        company: "Osteoporosis Canada",
        companyUrl: "https://osteoporosis.ca/",
        partnerUrl: "https://naryant.com/",
        role: "Machine Learning Researcher",
        duration: "May 2024 – Aug 2024",
        location: "Co-op · Oakville, Ontario",
        details: [
          "Collaborated on ML research and imminent fracture risk prediction.",
          "Engineered features, trained ensembles, and raised accuracy 30–40%.",
          "Documented outcomes for stakeholders and knowledge sharing.",
        ],
      },
      {
        company: "Freelance",
        role: "Full Stack Developer",
        duration: "Dec 2023 – May 2024",
        location: "Part-time · Remote",
        details: [
          "Delivered full-stack web applications for diverse clients.",
          "Built responsive frontends and scalable backends using modern frameworks.",
          "Managed end-to-end development lifecycle from design to deployment.",
        ],
      },
    ],
    content: [],
  },
  {
    id: "projects",
    label: "Projects",
    command: "projects",
    summary: "Selected builds with stack and links.",
    projects: [
      {
        name: "Loan Referral Automation",
        description:
          "Multi-tenant SaaS platform for a commercial loan broker. Referral partners submit deals through a portal while the broker manages the full pipeline. Borrowers get view-only access to their loan status.",
        stack: ["TypeScript", "Next.js", "Docker"],
        repoUrl: "https://github.com/rutts29/loan-referral-automation",
        liveUrl: "https://loan-ref.vercel.app/",
        image: "/projects/loan-ref-landing.png",
      },
      {
        name: "Keyed",
        description:
          "Decentralized social media platform built on Solana with AI-powered content discovery, creator monetization, and privacy tipping.",
        stack: ["TypeScript", "Rust", "Python", "Solana", "PostgreSQL"],
        repoUrl: "https://github.com/rutts29/Keyed",
        liveUrl: "https://frontend-beryl-omega-38.vercel.app/",
        image: "/projects/keyed-landing.png",
      },
    ],
    content: [],
  },
  {
    id: "contact",
    label: "Contact",
    command: "contact",
    summary: "Reach out via email or socials.",
    content: [],
    contactLinks: [
      {
        label: "rutts291@gmail.com",
        href: "mailto:rutts291@gmail.com",
        icon: "email",
      },
      {
        label: "linkedin.com/in/ruttansh-bhatelia",
        href: "https://www.linkedin.com/in/ruttansh-bhatelia",
        icon: "linkedin",
      },
      {
        label: "github.com/rutts29",
        href: "https://github.com/rutts29",
        icon: "github",
      },
      {
        label: "x.com/0xRutts",
        href: "https://x.com/0xRutts",
        icon: "x",
      },
      {
        label: "Toronto, Ontario · Open to relocate",
        icon: "location",
      },
    ],
  },
];

